更新工作流配置，添加从 subList 读取订阅链接的步骤，并发送请求到 subconverter 进行处理，同时新增 subList.csv 文件以存储链接

diff --git a/.github/workflows/Collector.yml b/.github/workflows/Collector.yml
--- a/.github/workflows/Collector.yml
+++ b/.github/workflows/Collector.yml
@@ -32,24 +32,57 @@ jobs:
         run: |
           go build -o myapp
           ./myapp -sort -log warn
-      
+
+      - name: Read subscription links from subList
+        id: read-links
+        run: |
+          ./tool/subconverter/subconverter &
+
+            until curl -s http://0.0.0.0:25500 >/dev/null; do
+              sleep 1
+            done
+          
+          if [ -f "subList.csv" ]; then
+            LINKS=$(cat subList | tr '\n' '|')
+            LINKS="${LINKS%|}"
+            echo "::set-output name=links::$LINKS"
+          else
+            echo "subList file not found."
+            exit 1
+          fi
+
+      - name: Send request to subconverter
+        id: subconverter-request
+        run: |
+          FULL_URL="http://0.0.0.0:25500/sub\?target\=mixed\&url\=${{ steps.read-links.outputs.links }}"
+          echo "Full URL: $FULL_URL"
+          curl -o ./results/mixed_base64.txt "$FULL_URL"
+          if [ $? -ne 0 ]; then
+            echo "Request to subconverter failed."
+            exit 1
+          fi
+
+      - name: Decode base64 and append to mixed.txt
+        run: |
+          base64 -d ./results/mixed_base64.txt >> ./results/mixed.txt
+
       - name: Speedtest
         run: |
           ./tool/speedTest_singtools/singtools test   -i ./results/mixed.txt -o ./results/mixed_tested.json -e fatal -f ""
-      
+
       - name: Convert to mixed with base64encode
         run: |
           ./tool/subconverter/subconverter &
-          
+
           until curl -s http://0.0.0.0:25500 >/dev/null; do
             sleep 1
           done
 
           # curl -o ./results/mixed_tested.txt http://0.0.0.0:25500/sub\?target\=mixed\&url\=./results/mixed_tested.json
-          
+
           # 执行 curl 命令并将结果保存到文件，同时添加错误检查
           full_url="http://0.0.0.0:25500/sub?target=mixed&url=$GITHUB_WORKSPACE/results/mixed_tested.json"
-          
+
           echo "\n------------------"
           echo "Full URL: $full_url"
           echo "\n------------------"
